### ISSUE TITLE
Adding the search functionality

### ISSUE THREAD

**Issue by pahulpreet-dev** [pahulpreet-dev/Dooramo#1]
We need to add the search functionality in the view requests activity

**Comment by haocencol** [comment]
Provide more detail.

**Comment by pahulpreet-dev** [comment]
When the residents post a request to the management, the management is able to view all the requests that have been made by all the residents. Also, the service providers are able to see all the requests under their particular specialty. We need to try to implement a search functionality so as the management and the service providers are able to search particular keywords. Implementation details will follow in coming days.

**Comment by pahulpreet-dev** [comment]
completed
