### ISSUE TITLE
Feedback System

### ISSUE THREAD

**Issue by AdavjeetBhangu** [pahulpreet-dev/Dooramo#4]
Adding new feature to the application. So that residents can provide feedback about the services done.

**Comment by haocencol** [comment]
Write this as a user story and then disaggregate into constituent tasks so that this story is more clear.  Right now, this is very vague.  What new feature?  How does a new feature and residents provide feedback about the services relate?

**Comment by pahulpreet-dev** [comment]
For this system, what we need to implement is new functionality for resident module under My Jobs section. As previously implemented, a resident goes to the My Jobs tab where he can see all the requests that were raised by him. As he clicks a job, he is migrated to another activity where he sees the details of the request. Now, here we will add a Feedback button for him to leave a feedback about the service provider. We need to implement the feedback button in a way that if the status of request is still "pending", then the resident won't be able to leave a feedback. In other words, a resident can only leave a feedback on a already completed job.
For the feedback, a resident should be able to rate and comment. On the management end, there will be new activity that will show list of all feedback. 
@Sukhman-Baath please do the design. I already created two issues for that. Please close when you are done.
@pahulpreet-dev I will do the feedback on the resident's end
@AdavjeetBhangu @ramandhaliwal1605 please do the management's end
Any suggestions are welcome. @AdavjeetBhangu @haocencol @ramandhaliwal1605 @Sukhman-Baath

**Comment by pahulpreet-dev** [comment]
Great job friends. Kudos everyone. @AdavjeetBhangu I like the way you used Hashmap<> to store the values of feedback and it's details. @Sukhman-Baath had great idea of re-using the already generated layouts to optimize the app and reduce the space. Thank you @ramandhaliwal1605 for finding all those little bugs and fixing them.

**Comment by AdavjeetBhangu** [comment]
Thank you for the appreciation buddy. All credits goes to you though. I just followed your advice. Cheers.
