### ISSUE TITLE
Migrate database.

### ISSUE THREAD

**Issue by ramandhaliwal1605** [pahulpreet-dev/Dooramo#5]
Migrating the database from localhost to cloud back-end. Bringing it online.

**Comment by haocencol** [comment]
Provide details:
1) Which cloud?
2) Which DB?
3) Any code to verify and confirm that the setup is correct?  That is, a simple program that writes in the DB and read back from the DB.

**Comment by pahulpreet-dev** [comment]
@ramandhaliwal1605 @AdavjeetBhangu @Sukhman-Baath we are focusing on this first. I will be migrating our project to online database. Then we will be discussing further steps.

**Comment by pahulpreet-dev** [comment]
We will be using Google's Firebase database services to change the local DB to online DB. The code will be reflected in the upcoming commits

**Comment by pahulpreet-dev** [comment]
I have added the Firebase services to our project. I am assigning the tasks to everyone to migrate all our database online. Use firebase docs to understand the working. Use this link https://firebase.google.com/docs/database/android/structure-data?authuser=2

Create new user, create new service provider, create new manager: @ramandhaliwal1605 
Check requests, view details of requests: @pahulpreet-dev 
Update request status (management console, service provider console): @AdavjeetBhangu 
Login: @Sukhman-Baath 

We will close this issue when above things are done.

**Comment by Sukhman-Baath** [comment]
to @ramandhaliwal1605 : i believe my part is partially dependent on your part. i will complete it as soon as you get yours done

**Comment by ramandhaliwal1605** [comment]
yes @Sukhman-Baath i am already working on it. I will get it done by March 3

**Comment by pahulpreet-dev** [comment]
we missed a module of "generating request by resident". @AdavjeetBhangu say he will do it.
