### ISSUE TITLE
SubmitFeedback system design

### ISSUE THREAD

**Issue by pahulpreet-dev** [pahulpreet-dev/Dooramo#7]
Need to add a button under RequestDetails activity that will open the feedback activity. This feedback activity will have five stars so user can select to rate the service provided out of five. The stars will be faded initially and light up as selected. For example, if star at position three is selected from the left, first three stars will light up. Further, we need to put a textarea where the user can leave a comment about the service provided.

**Comment by Sukhman-Baath** [comment]
Done according to above mentioned requirements
