### ISSUE TITLE
ViewFeedback design

### ISSUE THREAD

**Issue by pahulpreet-dev** [pahulpreet-dev/Dooramo#8]
We need to create a listView to show all the available feedback for management. As the user clicks on a feedback he will be prompted with new activity that has bunch of textviews showing details of the request that was raised and the feedback that was submitted by the resident.

**Comment by Sukhman-Baath** [comment]
I created a new activity for management to check all feedback. For inflating the ListView, we can use the request_layout_inflater again to populate the list. For showing details of the selected feedback, I just created a new Java class and selected the design of already existing RequestDetails activity as it has the similar kinds of textViews that are required by this new activity. All the activities are registered in the manifest as well

**Comment by pahulpreet-dev** [comment]
Great job @Sukhman-Baath thanks for valuable input. But I guess you forgot to add a button on management home page to navigate to CheckFeedback activity. @AdavjeetBhangu has got it covered and added it now.
