### ISSUE TITLE
SubmitFeedback implementation

### ISSUE THREAD

**Issue by Sukhman-Baath** [pahulpreet-dev/Dooramo#9]
This issue is explained by @pahulpreet-dev in #4

**Comment by pahulpreet-dev** [comment]
First when the resident clicks the Leave a feedback button, the app will check if the job is completed or not. The feedback option is available only to the completed jobs. Then, as the resident hits the submit feedback we are creating a new node in database named "requestFeedback" that has the child node with id same as that of the id of request and then it further have child nodes that has rating and comments stored in it. Structure of the firebase is as below:
requestFeedback: {
    requestID: {     //same as id of the original request
         rating: ""
         comment: ""
    }
}
